services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api_service
    working_dir: /app
    command: npm run start
    environment:
      - PORT=4000
      - NODE_ENV=production
      - CLOUD=aws
      - SSM_PARAMETER_PATH=/devconzero/env/
    networks:
      - dev_con_net
  frontend:
    build: ./frontend
    container_name: frontend_service
    networks:
      - dev_con_net
  web:
    image: nginx:alpine
    container_name: web_service
    ports:
      - "8080:80"
    volumes:
      # Mount the NGINX configuration file
      - ./web/prod/nginx.conf:/etc/nginx/nginx.conf:ro
      # - ./nginx/html:/usr/share/nginx/html
      - ./web/prod/logs:/var/log/nginx
    networks:
      - dev_con_net
    depends_on:
      - api
      - frontend
networks:
  dev_con_net:
    driver: bridge
    
    