FROM node:alpine

RUN apk add --no-cache aws-cli

# Set the working directory
WORKDIR /app
# Copy package.json and package-lock.json
COPY package*.json ./
COPY entrypoint.sh ./
RUN chmod +x entrypoint.sh

ENTRYPOINT [ "/entrypoint.sh" ]

RUN npm install
